/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

int main(){
    int n1 = 1;
    int n2 = 1;
    int res = 2;
    int sum = 0;
    while(res < 4000000){
        if(res % 2 == 0) sum += res;
        n1 = n2;
        n2 = res;
        res = n1+n2;
    }
    std::cout << sum << std::endl;
    return 0;
}